sources:
  - Danfo.glyphs
axisOrder:
  - ELSH
familyName: Danfo
buildVariable: True
stat:
  - name: Element Shape
    tag: ELSH
    values:
    - name: Regular
      value: 0
      flags: 2
    - name: Comb
      value: 50
    - name: Claw
      value: 100